### ISSUE TITLE
Multiple sheets

### ISSUE THREAD

**Issue by uwekolsch** [daikiueda/xlsx2json#5]
I noticed that in your library you just read the first sheet of the spreadsheet file, looking at it it seems to me that getting all data from the spreadsheet just requires to loop through all the sheets, is there any specific reason you did not implement this?

**Comment by daikiueda** [comment]
Hi uwekolsch,
I just released v1.0.0 and it support multiple-sheets.
Your notice motivated me. Thanks 😃
